-- CreateTable
CREATE TABLE "RaffleTicketPricing" (
    "id" TEXT NOT NULL,
    "paperCostPerSheet" DOUBLE PRECISION NOT NULL DEFAULT 0.45,
    "printingCostPerSheet" DOUBLE PRECISION NOT NULL DEFAULT 0.55,
    "cutCostPerSheet" DOUBLE PRECISION NOT NULL DEFAULT 0.20,
    "ticketsPerSheet" INTEGER NOT NULL DEFAULT 8,
    "wastePercent" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "setupFee" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "numberingSetupFee" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "numberingCostPerTicket" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
    "perforationSetupFee" DOUBLE PRECISION NOT NULL DEFAULT 10,
    "perforationCostPerTicket" DOUBLE PRECISION NOT NULL DEFAULT 0.03,
    "bookletCost" DOUBLE PRECISION NOT NULL DEFAULT 2,
    "defaultTicketsPerBook" INTEGER NOT NULL DEFAULT 50,
    "printReadyDesignFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "basicDesignFee" DOUBLE PRECISION NOT NULL DEFAULT 25,
    "fullDesignFee" DOUBLE PRECISION NOT NULL DEFAULT 50,
    "profitMargin" DOUBLE PRECISION NOT NULL DEFAULT 50,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RaffleTicketPricing_pkey" PRIMARY KEY ("id")
);
